name: Deploy to Environment

# Controls when the workflow will run
on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - staging
      - prod

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./kristiwg-oppg2

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }} # Only proceed if the PR was merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "env=dev" >> $GITHUB_ENV
            echo "tfvars_file=terraform.dev.tfvars" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "env=staging" >> $GITHUB_ENV
            echo "tfvars_file=terraform.staging.tfvars" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "env=prod" >> $GITHUB_ENV
            echo "tfvars_file=terraform.prod.tfvars" >> $GITHUB_ENV
          fi

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform workspace select or create
        run: terraform workspace select ${{ env.env }} || terraform workspace new ${{ env.env }}
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform apply
        run: terraform apply -auto-approve -var-file=${{ env.tfvars_file }}
        working-directory: ${{ env.WORKING_DIR }}

  # Production approval
  production:
    if: ${{ github.event.pull_request.merged == true && github.ref == 'refs/heads/prod' }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: 'kglomset@gmail.com'
          minimum-approvals: 1
          issue-title: "Approval required for Production Deployment"
          issue-body: "Please review and approve the changes for production deployment."
